owner: chowdhary-org
repo: status
sites:
  - name: Chowdhary.org
    url: https://chowdhary.org
assignees:
  - AnandChowdhary
status-website:
  logoUrl: https://avatars3.githubusercontent.com/u/68894094?s=200&v=4
  name: Chowdhary.org Status
  baseUrl: /status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
